[build-system]
requires = ["setuptools>=51.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80

[tool.isort]
profile = 'black'
line_length = 80

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
	"tests",
	"integration",
]
